# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [ published ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  integration:
    name: Stage Master Integration
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        ref: stage

    - name: Create Pull Request 
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        commit-message: Integrate stage to master on release published
        title: 'Stage to Master Integration'
        body: |
          Integrate stage to master on release published
        labels: automated pr, stage2master integration
        reviewers: helpbbcom
        base: master
        branch: stage

    - name: Check outputs
      run: |
        echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}":
