# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  release:
    types: [ published ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  integration:
    name: Stage Master Integration
    runs-on: ubuntu-latest

    env:
      GITHUB_CONTEXT: ${{ github.event.pull_request.commits_url }}
      run: echo "$GITHUB_CONTEXT"
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Dump GitHub context
      run: curl -o out.json ${{ github.event.pull_request.commits_url }}
      
    - name: GitHub Pull Request Action
      uses: repo-sync/pull-request@v2.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: "stage"
        destination_branch: "master"
        pr_title: "Integrating ${{ github.ref }} into master"
        pr_body: ":repeat: *Integrating ${{ github.ref }} into master*"
        pr_reviewer: "bbhelpcom"
        pr_assignee: "bbhelpcom"
        pr_label: "release integration"
        
